"""add tracking tables

Revision ID: bd1e66bb991d
Revises: 001
Create Date: 2026-01-29 14:37:24.047368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd1e66bb991d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('total_sodium_mg', sa.Float(), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein_g', sa.Float(), nullable=True),
    sa.Column('target_carbs_g', sa.Float(), nullable=True),
    sa.Column('target_fat_g', sa.Float(), nullable=True),
    sa.Column('num_meals', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_stats_user_id'), 'daily_stats', ['user_id'], unique=False)
    op.create_index('ix_daily_stats_user_date', 'daily_stats', ['user_id', 'date'], unique=True)
    op.create_table('meal_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('foods', sa.JSON(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('total_sodium_mg', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_consumed_at'), 'meal_logs', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=False),
    sa.Column('daily_protein_g', sa.Float(), nullable=False),
    sa.Column('daily_fat_g', sa.Float(), nullable=False),
    sa.Column('daily_carbs_g', sa.Float(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meals', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activitylevel'), nullable=False),
    sa.Column('diet_goal', sa.Enum('WEIGHT_LOSS', 'WEIGHT_GAIN', 'MAINTAIN', name='dietgoal'), nullable=False),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('disliked_foods', sa.JSON(), nullable=True),
    sa.Column('preferred_cuisines', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_food_nutrients_food_id'), 'food_nutrients', ['food_id'], unique=False)
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_index(op.f('ix_food_nutrients_food_id'), table_name='food_nutrients')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_consumed_at'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index('ix_daily_stats_user_date', table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_user_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
