"""
Script to import processed Foundation Foods data into the database.

This script reads the cleaned CSV files generated by process_foundation_foods.py
and inserts them into the PostgreSQL database.

Prerequisites:
1. Run process_foundation_foods.py first to generate the CSVs
2. Ensure the database is running (docker-compose up -d)
3. Run migrations (alembic upgrade head)

Run: python -m scripts.import_to_database
"""
import csv
import sys
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Optional
from uuid import UUID

from sqlmodel import Session, select

from app.database import engine
from app.models.food import Food, FoodNutrient, FoodSource

# Configuration
DATA_DIR = Path(__file__).parent.parent / "data/processed"
BATCH_SIZE = 100


def parse_decimal(value: str) -> Optional[Decimal]:
    """Safely parse a decimal value from string."""
    if not value or value.strip() == "" or value == "None":
        return None
    try:
        return Decimal(value.strip())
    except (InvalidOperation, ValueError):
        return None


def parse_bool(value: str) -> bool:
    """Parse boolean from string."""
    return value.lower() in ('true', '1', 'yes')


def parse_uuid(value: str) -> UUID:
    """Parse UUID from string."""
    return UUID(value.strip())


def parse_datetime(value: str) -> datetime:
    """Parse datetime from ISO format string."""
    # Handle timezone-aware datetime
    if value.endswith('+00:00'):
        return datetime.fromisoformat(value)
    # Handle naive datetime, assume UTC
    return datetime.fromisoformat(value.replace('Z', '+00:00'))


def count_existing_foods(session: Session) -> int:
    """Count existing foods in the database."""
    result = session.exec(select(Food)).all()
    return len(result)


def import_foods(session: Session, foods_file: Path) -> dict:
    """
    Import foods from CSV into database.
    Returns mapping of {csv_id: db_food} for nutrient linking.
    """
    print(f"  Reading {foods_file}...")

    foods_map = {}
    batch = []
    imported = 0
    skipped = 0

    with open(foods_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        for row in reader:
            csv_id = row['id']
            usda_id = row['usda_id']

            # Check if food already exists (by usda_id)
            existing = session.exec(
                select(Food).where(Food.usda_id == usda_id)
            ).first()

            if existing:
                foods_map[csv_id] = existing
                skipped += 1
                continue

            # Check if name_normalized already exists
            name_normalized = row['name_normalized']
            existing_name = session.exec(
                select(Food).where(Food.name_normalized == name_normalized)
            ).first()

            if existing_name:
                foods_map[csv_id] = existing_name
                skipped += 1
                continue

            # Create new food
            food = Food(
                id=parse_uuid(csv_id),
                name=row['name'],
                name_normalized=name_normalized,
                category=row['category'] if row['category'] else None,
                serving_size_g=parse_decimal(row['serving_size_g']) or Decimal('100'),
                serving_unit=row['serving_unit'] or 'g',
                calorie_per_100g=parse_decimal(row['calorie_per_100g']),
                usda_id=usda_id,
                source=FoodSource.USDA,
                is_verified=parse_bool(row['is_verified']),
                embedding=None,
            )

            batch.append(food)
            foods_map[csv_id] = food

            # Process batch
            if len(batch) >= BATCH_SIZE:
                session.add_all(batch)
                session.flush()
                imported += len(batch)
                print(f"    Imported {imported} foods...")
                batch = []

        # Process remaining
        if batch:
            session.add_all(batch)
            session.flush()
            imported += len(batch)

    print(f"  Foods imported: {imported}, skipped (already exist): {skipped}")
    return foods_map


def import_nutrients(session: Session, nutrients_file: Path, foods_map: dict) -> int:
    """Import food nutrients from CSV into database."""
    print(f"  Reading {nutrients_file}...")

    batch = []
    imported = 0
    skipped = 0

    with open(nutrients_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        for row in reader:
            csv_food_id = row['food_id']

            # Get the actual food from our mapping
            food = foods_map.get(csv_food_id)
            if not food:
                skipped += 1
                continue

            # Check if nutrient already exists for this food
            existing = session.exec(
                select(FoodNutrient).where(FoodNutrient.food_id == food.id)
            ).first()

            if existing:
                skipped += 1
                continue

            # Create new nutrient record
            nutrient = FoodNutrient(
                id=parse_uuid(row['id']),
                food_id=food.id,
                calories_100g=parse_decimal(row['calories_100g']),
                protein_g_100g=parse_decimal(row['protein_g_100g']),
                carbs_g_100g=parse_decimal(row['carbs_g_100g']),
                fat_g_100g=parse_decimal(row['fat_g_100g']),
                saturated_fat_g_100g=parse_decimal(row['saturated_fat_g_100g']),
                fiber_g_100g=parse_decimal(row['fiber_g_100g']),
                sugar_g_100g=parse_decimal(row['sugar_g_100g']),
                sodium_mg_100g=parse_decimal(row['sodium_mg_100g']),
                calcium_mg_100g=parse_decimal(row['calcium_mg_100g']),
                iron_mg_100g=parse_decimal(row['iron_mg_100g']),
                vitamin_c_mg_100g=parse_decimal(row['vitamin_c_mg_100g']),
            )

            batch.append(nutrient)

            # Process batch
            if len(batch) >= BATCH_SIZE:
                session.add_all(batch)
                session.flush()
                imported += len(batch)
                print(f"    Imported {imported} nutrient records...")
                batch = []

        # Process remaining
        if batch:
            session.add_all(batch)
            session.flush()
            imported += len(batch)

    print(f"  Nutrients imported: {imported}, skipped: {skipped}")
    return imported


def main():
    print("=== Database Import ===\n")

    # Check data files exist
    foods_file = DATA_DIR / "foods.csv"
    nutrients_file = DATA_DIR / "food_nutrients.csv"

    if not foods_file.exists():
        print(f"Error: {foods_file} not found")
        print("Run 'python -m scripts.process_foundation_foods' first")
        sys.exit(1)

    if not nutrients_file.exists():
        print(f"Error: {nutrients_file} not found")
        sys.exit(1)

    print(f"Data directory: {DATA_DIR}")
    print(f"Foods file: {foods_file}")
    print(f"Nutrients file: {nutrients_file}")

    with Session(engine) as session:
        # Check existing data
        existing_count = count_existing_foods(session)
        print(f"\nExisting foods in database: {existing_count}")

        # Import foods
        print("\n1. Importing foods...")
        foods_map = import_foods(session, foods_file)

        # Import nutrients
        print("\n2. Importing nutrients...")
        import_nutrients(session, nutrients_file, foods_map)

        # Commit all changes
        print("\n3. Committing to database...")
        session.commit()

        # Final count
        final_count = count_existing_foods(session)
        print(f"\n=== Import Complete ===")
        print(f"Total foods in database: {final_count}")
        print(f"New foods added: {final_count - existing_count}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}")
        raise
